[package]
name = "rc-magic-link"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.132", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
hmac = "0.11.0"
sha2 = "0.9.0"
bincode = "1.3.3"
fastrand = "1.6.0"
hex = "0.4.3"
