[package]
name = "rc-msgdb"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.0"
sled = "0.34.7"
thiserror = "1.0.30"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
tempfile = "3.2.0"

[[bench]]
name = "db"
harness = false
