name: Book

on:
  schedule:
    - cron: "0 2 * * *"

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.NEW_GEN_ACTIONS_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.VOCECHAT_COM_HOST }} >> ~/.ssh/known_hosts
      - name: Install rsync
        run: ${{ matrix.pre_install }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - name: Build Book
        run: |
          cargo install --git https://github.com/rust-lang/mdBook.git mdbook
          ~/.cargo/bin/mdbook build book/en-us -d ../target/en-us
          rsync -av book/target/* root@${{ secrets.VOCECHAT_COM_HOST }}:/home/wwwroot/doc.voce.chat/
