name: CI

on:
  schedule:
    - cron: "0 1 * * *"
    
#on:
#  push:
#    branches:
#      - main
#  pull_request: { }

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      # Use nightly Rust to check the format
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Check format
        run: cargo fmt --all -- --check

      # Switch to stable Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56.1
          override: true
          components: rustfmt, clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - name: Check with clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test

